FROM python:3.9

WORKDIR /usr/src/app

# Set environment variables
ENV ACCEPT_TIME_DIFFERENCE_MINUTES=${ACCEPT_TIME_DIFFERENCE_MINUTES} \
    BASE_RATE=${BASE_RATE} \
    CACHE_REDIS_DB=${CACHE_REDIS_DB} \
    CACHE_REDIS_HOST=${CACHE_REDIS_HOST} \
    CACHE_REDIS_PORT=${CACHE_REDIS_PORT} \
    CACHE_TYPE=${CACHE_TYPE} \
    COST_PER_KM=${COST_PER_KM} \
    DB_HOST=${DB_HOST} \
    DB_NAME=${DB_NAME} \
    DB_PORT=${DB_PORT} \
    DB_PWD=${DB_PWD} \
    DB_USER=${DB_USER} \
    FRONT_END_URL=${FRONT_END_URL} \
    GOOGLE_API_KEY=${GOOGLE_API_KEY} \
    JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES} \
    JWT_SALT=${JWT_SALT} \
    JWT_SECRET_KEY=${JWT_SECRET_KEY} \
    MAIL_EXPIRATION=${MAIL_EXPIRATION} \
    MAIL_PASSWORD=${MAIL_PASSWORD} \
    MAIL_SERVER=${MAIL_SERVER} \
    MAIL_USERNAME=${MAIL_USERNAME} \
    MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH} \
    RATE_PER_KM=${RATE_PER_KM} \
    ROUTE_CHECKER=${ROUTE_CHECKER} \
    RQ_REDIS_URL=${RQ_REDIS_URL} \
    SECRET_KEY=${SECRET_KEY} \
    SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT} \
    UNIVERSITY_CITY=${UNIVERSITY_CITY} \
    UNIVERSITY_EMAIL_DOMAIN=${UNIVERSITY_EMAIL_DOMAIN} \
    UNIVERSITY_POSTAL_CODE=${UNIVERSITY_POSTAL_CODE} \
    UNIVERSITY_STREET_NAME=${UNIVERSITY_STREET_NAME} \
    UNIVERSITY_STREET_NUMBER=${UNIVERSITY_STREET_NUMBER}

COPY . .

RUN pip install -e .

EXPOSE 5050

CMD [ "python3", "uniride_sme/rest_api.py"]
