FROM python:3.10

WORKDIR /usr/src/app

#Set arguments
ARG ACCEPT_TIME_DIFFERENCE_MINUTES
ARG BASE_RATE
ARG CACHE_REDIS_DB
ARG CACHE_REDIS_HOST
ARG CACHE_REDIS_PORT
ARG CACHE_TYPE
ARG COST_PER_KM
ARG DB_HOST
ARG DB_NAME
ARG DB_PORT
ARG DB_PWD
ARG DB_USER
ARG FRONT_END_URL
ARG GOOGLE_API_KEY
ARG JWT_ACCESS_TOKEN_EXPIRES
ARG JWT_SALT
ARG JWT_SECRET_KEY
ARG MAIL_EXPIRATION
ARG MAIL_PASSWORD
ARG MAIL_SERVER
ARG MAIL_USERNAME
ARG MAX_CONTENT_LENGTH
ARG RATE_PER_KM
ARG ROUTE_CHECKER
ARG RQ_REDIS_URL
ARG SECRET_KEY
ARG SECURITY_PASSWORD_SALT
ARG UNIVERSITY_CITY
ARG UNIVERSITY_EMAIL_DOMAIN
ARG UNIVERSITY_POSTAL_CODE
ARG UNIVERSITY_STREET_NAME
ARG UNIVERSITY_STREET_NUMBER
ARG FLASK_DEBUG
ARG FLASK_HOST
ARG FLASK_PORT
ARG PFP_UPLOAD_FOLDER
ARG LICENSE_UPLOAD_FOLDER
ARG ID_CARD_UPLOAD_FOLDER
ARG SCHOOL_CERTIFICATE_UPLOAD_FOLDER
ARG CERTIFICATE_CRT_FOLDER
ARG CERTIFICATE_KEY_FOLDER

# Set environment variables, maybe for specific variables we can move them to the docker-compose file
ENV ACCEPT_TIME_DIFFERENCE_MINUTES=$ACCEPT_TIME_DIFFERENCE_MINUTES \
    BASE_RATE=$BASE_RATE \
    CACHE_REDIS_DB=$CACHE_REDIS_DB \
    CACHE_REDIS_HOST=$CACHE_REDIS_HOST \
    CACHE_REDIS_PORT=$CACHE_REDIS_PORT \
    CACHE_TYPE=$CACHE_TYPE \
    COST_PER_KM=$COST_PER_KM \
    DB_HOST=$DB_HOST \
    DB_NAME=$DB_NAME \
    DB_PORT=$DB_PORT \
    DB_PWD=$DB_PWD \
    DB_USER=$DB_USER \
    FRONT_END_URL=$FRONT_END_URL \
    GOOGLE_API_KEY=$GOOGLE_API_KEY \
    JWT_ACCESS_TOKEN_EXPIRES=$JWT_ACCESS_TOKEN_EXPIRES \
    JWT_SALT=$JWT_SALT \
    JWT_SECRET_KEY=$JWT_SECRET_KEY \
    MAIL_EXPIRATION=$MAIL_EXPIRATION \
    MAIL_PASSWORD=$MAIL_PASSWORD \
    MAIL_SERVER=$MAIL_SERVER \
    MAIL_USERNAME=$MAIL_USERNAME \
    MAX_CONTENT_LENGTH=$MAX_CONTENT_LENGTH \
    RATE_PER_KM=$RATE_PER_KM \
    ROUTE_CHECKER=$ROUTE_CHECKER \
    RQ_REDIS_URL=$RQ_REDIS_URL \
    SECRET_KEY=$SECRET_KEY \
    SECURITY_PASSWORD_SALT=$SECURITY_PASSWORD_SALT \
    UNIVERSITY_CITY=$UNIVERSITY_CITY \
    UNIVERSITY_EMAIL_DOMAIN=$UNIVERSITY_EMAIL_DOMAIN \
    UNIVERSITY_POSTAL_CODE=$UNIVERSITY_POSTAL_CODE \
    UNIVERSITY_STREET_NAME=$UNIVERSITY_STREET_NAME \
    UNIVERSITY_STREET_NUMBER=$UNIVERSITY_STREET_NUMBER \
    FLASK_DEBUG=$FLASK_DEBUG \
    FLASK_HOST=$FLASK_HOST \
    FLASK_PORT=$FLASK_PORT\
    PFP_UPLOAD_FOLDER=$PFP_UPLOAD_FOLDER \
    LICENSE_UPLOAD_FOLDER=$LICENSE_UPLOAD_FOLDER \
    ID_CARD_UPLOAD_FOLDER=$ID_CARD_UPLOAD_FOLDER \
    SCHOOL_CERTIFICATE_UPLOAD_FOLDER=$SCHOOL_CERTIFICATE_UPLOAD_FOLDER \
    CERTIFICATE_CRT_FOLDER=$CERTIFICATE_CRT_FOLDER \
    CERTIFICATE_KEY_FOLDER=$CERTIFICATE_KEY_FOLDER 

# Copy pyproject.toml first to avoid reinstalling dependencies when code changes
COPY pyproject.toml . 

COPY . .

RUN pip install -e .

EXPOSE 5050

ENTRYPOINT [ "python3" ]

CMD ["uniride_sme/rest_api.py"]