FROM python:3.10

WORKDIR /usr/src/app

#Set arguments
ARG ROUTE_CHECKER
ARG RATE_PER_KM
ARG COST_PER_KM
ARG BASE_RATE
ARG ACCEPT_TIME_DIFFERENCE_MINUTES
ARG MAIL_EXPIRATION
ARG MAX_CONTENT_LENGTH
ARG JWT_ACCESS_TOKEN_EXPIRES
ARG JWT_ACCESS_TOKEN_REFRESH
ARG JWT_REFRESH_TOKEN_EXPIRES
ARG CACHE_TYPE
ARG CACHE_REDIS_DB
ARG FLASK_DEBUG
ARG PFP_UPLOAD_FOLDER
ARG LICENSE_UPLOAD_FOLDER
ARG ID_CARD_UPLOAD_FOLDER
ARG SCHOOL_CERTIFICATE_UPLOAD_FOLDER
ARG INSURANCE_UPLOAD_FOLDER

# Set environment variables, maybe for specific variables we can move them to the docker-compose file
ENV ROUTE_CHECKER=$ROUTE_CHECKER \
    RATE_PER_KM=$RATE_PER_KM \
    COST_PER_KM=$COST_PER_KM \
    BASE_RATE=$BASE_RATE \
    ACCEPT_TIME_DIFFERENCE_MINUTES=$ACCEPT_TIME_DIFFERENCE_MINUTES \
    MAIL_EXPIRATION=$MAIL_EXPIRATION \
    MAX_CONTENT_LENGTH=$MAX_CONTENT_LENGTH \
    JWT_ACCESS_TOKEN_EXPIRES=$JWT_ACCESS_TOKEN_EXPIRES \
    JWT_ACCESS_TOKEN_REFRESH=$JWT_ACCESS_TOKEN_REFRESH \
    JWT_REFRESH_TOKEN_EXPIRES=$JWT_REFRESH_TOKEN_EXPIRES \
    CACHE_TYPE=$CACHE_TYPE \
    CACHE_REDIS_DB=$CACHE_REDIS_DB \
    FLASK_DEBUG=$FLASK_DEBUG \
    PFP_UPLOAD_FOLDER=$PFP_UPLOAD_FOLDER \
    LICENSE_UPLOAD_FOLDER=$LICENSE_UPLOAD_FOLDER \
    ID_CARD_UPLOAD_FOLDER=$ID_CARD_UPLOAD_FOLDER \
    SCHOOL_CERTIFICATE_UPLOAD_FOLDER=$SCHOOL_CERTIFICATE_UPLOAD_FOLDER \
    INSURANCE_UPLOAD_FOLDER=$INSURANCE_UPLOAD_FOLDER

# Copy pyproject.toml first to avoid reinstalling dependencies when code changes
COPY pyproject.toml . 

COPY . .

RUN pip install -e .

# Set timezone to Paris, France
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 5050

ENTRYPOINT [ "python3" ]

CMD ["uniride_sme/rest_api.py"]